# otel-collector-otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  hostmetrics:
    collection_interval: 60s
    scrapers:
      # CPU utilization metrics
      cpu:
      # Disk I/O metrics
      disk:
      # File System utilization metrics
      filesystem:
      # CPU load metrics
      load:
      # Memory utilization metrics
      memory:
      # Network interface I/O metrics & TCP connection metrics
      network:
      # Paging/Swap space utilization and I/O metrics
      paging:

processors:
  batch:
  probabilistic_sampler:
    hash_seed: 22
    sampling_percentage: 20
exporters:
  otlp:
    endpoint: "api.honeycomb.io:443" # US instance
    headers:
      "x-honeycomb-team": "${env:OTEL_HONEYCOMB_APIKEY}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [probabilistic_sampler, batch]
      exporters: [otlp]
    metrics:
        receivers: [ otlp, hostmetrics ]
        processors: [ batch ]
        exporters: [ otlp ]
  telemetry:
    logs:
      level: INFO
    metrics:
      level: none