# otel-collector-otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  probabilistic_sampler:
    hash_seed: 22
    sampling_percentage: 100
exporters:
  otlp:
    endpoint: "api.honeycomb.io:443" # US instance
    headers:
      "x-honeycomb-team": "${env:OTEL_HONEYCOMB_APIKEY}"

  otlp/signoz:
    endpoint: http://51.195.254.28:4317
    tls:
      insecure: true
      insecure_skip_verify: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [probabilistic_sampler, batch]
      exporters: [otlp, otlp/signoz]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp, otlp/signoz ]
  telemetry:
    logs:
      level: INFO
    metrics:
      level: none