# otel-collector-otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  tail_sampling:
    policies:
      # Sample only 20% of the traces
      - name: probability sampler
        type: probabilistic
        probabilistic: { sampling_percentage: 20 }
      # Always sample errors
      - name: error sampler
        type: status_code
        status_code: { status_codes: [ ERROR ] }

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443" # US instance
    headers:
      "x-honeycomb-team": "${env:OTEL_HONEYCOMB_APIKEY}"
  otlp/signoz:
    endpoint: http://51.195.254.28:4317
    tls:
      insecure: true
      insecure_skip_verify: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ tail_sampling, batch ]
      exporters:
        - otlp
    #       - otlp/signoz
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters:
        - otlp
  #       - otlp/signoz
  telemetry:
    logs:
      level: DEBUG
    metrics:
      level: none